### ISSUE TITLE
[UNRESOLVED] The BT Diagram disappear after closing the Eclipse

### ISSUE THREAD

**Issue by bangau1** [mrzon/GraphBT#6]
Scenario:
- Saving the BT Diagram (into .btdiagram and .model) and closing the Eclipse
- Open Eclipse again
- Open .btdiagram saved before
- The diagrams are disappear (blank canvas).

**Comment by bangau1** [comment]
Status 14/08/2012: This issue is still showing in current branch (master3branch_validate_merged)

**Comment by mrzon** [comment]
as far as i know, it might be automatically added if it is a real plugin. My assumption is because the plugin is always be rebuild so one version of plugin will not work with the newer.. so @bangau1 please test it by make it a plugin, install it, and test it.. then report your testing result.. thanks
